### ISSUE TITLE
Not Found gametxt

### ISSUE THREAD

**Issue by HerlanderAlmeida** [kurt-stolle/node-gamequery#20]
When installed by npm does not find in the package the file "game.txt"

return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

Error: ENOENT: no such file or directory, open '/app/node_modules/gamequery/games.txt'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.readFileSync (fs.js:508:33)
at readGames (/app/node_modules/gamequery/lib/typeresolver.js:25:17)
at Object.<anonymous> (/app/node_modules/gamequery/lib/typeresolver.js:46:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/app/node_modules/gamequery/lib/index.js:5:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

**Comment by kurt-stolle** [comment]
Not sure what happened here. I've republished the stable version to NPM, and can now no longer recreate the issue.
